# Generated by Django 3.2.25 on 2025-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
