# Generated by Django 3.2.25 on 2025-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_description', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
