# Generated by Django 3.2.25 on 2025-04-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='physical_or_digital',
            new_name='physical_or_digital_type',
        ),
    ]
