# Generated by Django 3.2.25 on 2025-04-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_physical_or_digital_orderlineitem_physical_or_digital_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='physical_or_digital_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
