# Generated by Django 3.2.25 on 2025-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='gameproduct',
            name='physical_or_digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
