# Generated by Django 3.2.25 on 2025-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproduct',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
