# Generated by Django 3.2.25 on 2025-04-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_gameproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
